### PR TITLE
Re-added the attribution to Cryptex, and the Original Devs.

### PR DESCRIPTION
**Pull request by marvhus**
Added Cythes, and Mart to the list of Original Devs
(actual list of Original Devs: https://github.com/SSGorg/Cryptex-old/graphs/contributors )

### CODE REVIEW

**Comment by PrettyBoyCosmo** [comment]
We have already given SSG appropriate accreditation in the `README.md` file of the repository. Keep in mind you haven't even mentioned us at all in your version of the repo. Kind of hypocritical no?

**Comment by marvhus** [comment]
@PrettyBoyCosmo 
> Keep in mind you haven't even mentioned us at all in your version of the repo. Kind of hypocritical no?

The new version contains none of your code, and thus needs no attribution.
It was a complete rewrite.

And the original repo, that you worked on, is the repo you based SkeletonKey on.
The original repo hasn't been touched since the split, so if you claim there is too little attribution there, that is your fault.

> We have already given SSG appropriate accreditation in the README.md file of the repository.

What you wrote in the README.md file is far from appropriate accediation. 
And you even removed names from the list of original developers. (https://github.com/CosmodiumCS/SkeletonKey/commit/3e7f392bb3812170cd5f39c0aa28f3547d4e7c2c?diff=unified#diff-01e6d9ffed056a02cae8d8a0ec5d476a64d017bf85c0d5a94bb23ca21f33f5aaL171-R145)

Note:
That image you attached is from the new repo (https://github.com/SSGorg/Cryptex), and not the old repo (https://github.com/SSGorg/Cryptex-old). The old one contains the correct attribution. As mentioned above the new one needs no attribution since it is all our code.

**Comment by Soulsender** [comment]
In that case we will remove the rest of your code from the project and we will remove your credit. Should you decide to commit some more working code, we will credit you at the very bottom of the README as per usual.

**Comment by marvhus** [comment]
> In that case we will remove the rest of your code from the project and we will remove your credit. Should you decide to commit some more working code, we will credit you at the very bottom of the README as per usual.

Then you better make sure you remove ALL of it.

This should help out https://github.com/SSGorg/Cryptex-old/commits?author=marvhus

**Comment by Soulsender** [comment]
We definitely will, but as I mentioned, should you like to re-commit new code, you can find a tutorial on python [here]( https://www.cosmodiumcs.com/courses) to get you started with the python programming language. Unfortunately, it's not compiled like Rust, but this will probably make it easier for you to use since it's more beginner friendly.

**Comment by PrettyBoyCosmo** [comment]
> Then you better make sure you remove ALL of it.

**SIR YES SIR!!**
smiley-salute

**Comment by marvhus** [comment]
> We definitely will, but as I mentioned, should you like to re-commit new code, you can find a tutorial on python [here](https://www.cosmodiumcs.com/courses) to get you started with the python programming language. Unfortunately, it's not compiled like Rust, but this will probably make it easier for you to use since it's more beginner friendly.

```py
import random
random.seed(3405691582)
print(''.join([chr((int("05E420A7A9C0591AE3EA01F0A5"[b:b+2],16)+random.randint(0,254))%255)for b in range(0,len("05E420A7A9C0591AE3EA01F0A5"),2)]))
```
@Soulsender the above code may be of use.

**Comment by marvhus** [comment]
btw, there is still unattributed code by me in the repo.

**Comment by rt-leaks** [comment]
we living rent free in this mofos head

**Comment by marvhus** [comment]
> we living rent free in this mofos head

You're living rent free on others code.

**Comment by Soulsender** [comment]
image

**Comment by Soulsender** [comment]
image

**Comment by wyrdCCS** [comment]
@marvhus Can you give examples of code that you added that isn't attributed? If there is code that you haven't been given credit for, we do need to fix this, but at the moment you aren't pointed at anything specific.

**Comment by marvhus** [comment]
> @marvhus Can you give examples of code that you added that isn't attributed? If there is code that you haven't been given credit for, we do need to fix this, but at the moment you aren't pointed at anything specific.

I currently don't have enough time to point out all of it, but it should be relatively easy to find it using `git blame` (https://git-scm.com/docs/git-blame), GitHub also has a built in version of git blame.

Since you removed the git history it won't be as easy, but you should be able to do it from comparing the code that remains from this commit: 4e3f541441d26908ac9505274f257e8ecb51c8ef (and maybe some other commits too, since it seams like you have deleted and re-uploaded parts of the code here and there), and the last commit from the archived version of Cryptex: https://github.com/SSGorg/Cryptex-old

If you can't or won't remove code by me, then add **proper attribution**, if not, remove it.
No "it's one line of code, it can't be licensed" bullshit, either you remove it, or you add attribution.

Also, it would be nice if you added attribution to the other devs who also worked on Cryptex, and not just the ones that ask for attribution or to have their code removed. Also, it seams like you removed all mention of Cryptex, and I'm not 100% sure how legal that is, but you may want to look into that.

**Comment by Soulsender** [comment]
Find an actual sample of code and we will look over it and remove it if we deem it valid as your commitment. However, importing a module and using that as a function of the program is not unique enough to be considered "your code".

Additionally, I will update to credit the rest of the people who did work on the project however, as we haven't completely removed their code yet.

Additionally, if you can find somewhere in the AGPL license that we use that says that we in fact still have to include you, then let us know, because I am definitely not going to be looking through the license for you. 

Also, I think it's funny you've edited almost every one of your comments to make us look as bad as possible, and to make you look more professional than you are. Why don't you spend your time doing something actually productive instead of spreading rumors about us, and demanding that we owe you something more. Grow up.
image

**Comment by marvhus** [comment]
> Find an actual sample of code and we will look over it and remove it if we deem it valid as your commitment. However, importing a module and using that as a function of the program is not unique enough to be considered "your code".

1. Fine
   - https://github.com/CosmodiumCS/MK15-SkeletonKey/blob/main/main.py#L158-L162 -- https://github.com/SSGOrg/Cryptex-old/commit/326aef053c8c7c366487f5d04f60b1e3b90441f0#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R119-R123 -- cli arguments that I added for the googletranslate cipher (the cipher was removed, but this still remains)
   - https://github.com/CosmodiumCS/MK15-SkeletonKey/blob/main/main.py#L213 -- https://github.com/SSGOrg/Cryptex-old/commit/d07548a2632b102b3a48eff7439cc81f22545f08?diff=unified#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1L205 -- Removed repetition by adding a func variable and setting the function pointer thing to it, then using it.
   - https://github.com/CosmodiumCS/MK15-SkeletonKey/blob/main/ciphers/cc.py#L38 -- https://github.com/SSGOrg/Cryptex-old/commit/113dce92cafc5dcf6182b7690a9474678d9e9505#diff-3428918f16d12f79c559f16155da4c276896a89f77d26f8a1db7aac44796fe67L45 -- Changed it from a hardcoded symbols list, to an argument to the cipher
   - https://github.com/CosmodiumCS/MK15-SkeletonKey/blob/main/ciphers/md5.py#L64 -- https://github.com/SSGOrg/Cryptex-old/blame/master/ciphers/md5.py#L54 -- Added brute forcing to md5
   - https://github.com/CosmodiumCS/MK15-SkeletonKey/blob/main/ciphers/r13.py#L27 -- https://github.com/SSGOrg/Cryptex-old/blame/master/ciphers/r13.py#L27 -- Made r13 call to cc by importing it instead of running a shell command.  

These are the ones I found after a quick look.

2. It's still a comtribution to the code by me. If you don't want to remove it then **ADD ATTRIBUTION**

> Additionally, I will update to credit the rest of the people who did work on the project however, as we haven't completely removed their code yet.

You haven't completely removed mine yet.

> Also, I think it's funny you've edited almost every one of your comments to make us look as bad as possible, and to make you look more professional than you are. Why don't you spend your time doing something actually productive instead of spreading rumors about us, and demanding that we owe you something more. Grow up. image

All of the ones I've edited except one I edited right after to fix typos I saw after the fact, or to add things that I forgot to add when posting it.  
The only one that was edited way after the fact was the one you have screenshoted. But if you looked further into the edit you would realize that I did not make it "more profesional", at least not in my opinion.  
Also, on GitHub you can see what the previous version of the comment was, so saying that I'm editing them to look more professional is just bulshit.  
Don't just look and see that it says `editied` and assume that it's a mojor change to the comment to make you look bad, click on them and see what the edits actually are. What you are doing now is literally spreading rumors... how ironic.  
Lastly, I haven't spread any rumors about you.

**Comment by marvhus** [comment]
@Soulsender also, I just noticed.
It's kinda hypocritical of you to complain about me editing my comments, when you have edited your comment complaining about it 6 times. Removing parts, adding parts, and editing parts.  
Calm down, and stop pretending that you are better than others.

**Comment by Soulsender** [comment]
> @Soulsender also, I just noticed.
> It's kinda hypocritical of you to complain about me editing my comments, when you have edited your comment complaining about it 6 times. Removing parts, adding parts, and editing parts.
> Calm down, and stop pretending that you are better than others.

Never said I was better at anyone in anything. I have respect for the people who are better at me in somethings, but that does not include you. 

There is a difference between editing your comment BEFORE someone replies as opposed to AFTER. Didn’t think I’d have to explain this to you, but when I edited that last comment, I wasn’t backpedaling on my words, I was adding to it.

**Comment by marvhus** [comment]
> Never said I was better at anyone in anything.

You kinda implied that you were, but sure.

> There is a difference between editing your comment BEFORE someone replies as opposed to AFTER. Didn’t think I’d have to explain this to you, but when I edited that last comment, I wasn’t backpedaling on my words, I was adding to it.

Please give an example of when I have backpedaled on a comment here.
I doubt that you'll find one.
(Note: the one saying "fuck you soul" doesn't count even though you may think so, since the comment basically says the same now too)

Also you technically did backpedal on saying this:
> I don't believe that we need to actually disclose that you worked on this project, as the credit is in the git history, but since you no longer work on the project, and we have no more of your code in the project.

image

**Comment by wyrdCCS** [comment]
Hey @marvhus I looked into the code samples you listed above. I have added a mention and link back to the original project. I had not looked at the README.md till just a bit ago. I am sorry that was removed. Is this ok for attribution? 

```
We would like to give a specal thanks to the team at SSG. This started as a comunity project between CCS and SSG. The original project can be found here. [Cryptex](https://github.com/SSGOrg/Cryptex-old)
```

**Comment by marvhus** [comment]
> Hey @marvhus I looked into the code samples you listed above. I have added a mention and link back to the original project. I had not looked at the README.md till just a bit ago. I am sorry that was removed. Is this ok for attribution? 
> 
> ```
> We would like to give a specal thanks to the team at SSG. This started as a comunity project between CCS and SSG. The original project can be found here. [Cryptex](https://github.com/SSGOrg/Cryptex-old)
> ```
>  

I would still like credit to individual devs, but that works for now. Just make sure you don't decide to suddenly remove it again.

**Comment by wyrdCCS** [comment]
Hey @marvhus. That is why I have linked the old repo. This project has it roots in the original cryptex and was the base of this project, but after the move was made the devs listed on the page are the ones that put the work into this. I want to keep the old repo listed as that is where the GIT history shows all the work done by the legacy team. To add the others from the legacy team in that way would be giving them credit for the work the current SkeletonKey team has done. By leaving the legacy repo in the readme it shows that they do still live on in the project and are recognized in its infancy. The note in the readme won't be removed and the link in the credits page will also stay. Ideally the  project would have been forked from the original repo but unfortunately that wasn't done.  This leaves the work done be SSG in the original project in a place where it could be swept under the rug and I am sorry about that. I know some tension exist because of the project and other outside things, but that won't be the case from the CCS team any more. Please let me know if this leaves something un-resolved so we can fix this without any more back and forth.

Respectfully and peacefully,
Matze

**Comment by marvhus** [comment]
> Hey @marvhus. That is why I have linked the old repo. This project has it roots in the original cryptex and was the base of this project, but after the move was made the devs listed on the page are the ones that put the work into this. I want to keep the old repo listed as that is where the GIT history shows all the work done by the legacy team. To add the others from the legacy team in that way would be giving them credit for the work the current SkeletonKey team has done. By leaving the legacy repo in the readme it shows that they do still live on in the project and are recognized in its infancy. The note in the readme won't be removed and the link in the credits page will also stay. Ideally the project would have been forked from the original repo but unfortunately that wasn't done. This leaves the work done be SSG in the original project in a place where it could be swept under the rug and I am sorry about that. I know some tension exist because of the project and other outside things, but that won't be the case from the CCS team any more. Please let me know if this leaves something un-resolved so we can fix this without any more back and forth.
> 
> Respectfully and peacefully, Matze

I can agree with that, though Soul did add in some attribution for work on Cryptex, but not Skeleton key, which goes against your argument, so you may want to look into that.  
https://github.com/CosmodiumCS/MK15-SkeletonKey/commit/9c8aa5c5030f2988e950522b8bba0a9281c53450

**Comment by wyrdCCS** [comment]
Hey, @marvhus! Just like this situation, Alex (Cythes) also requested to be listed. We agreed to add him in that section after talking with his. That conversation was done in discord. We have asked him questions about a few things that have been added here but aren't shown in the git history so we kept him listed as a way to still show that.

Please let me know if you have any more questions, or if this explanation gets us to a stable place.

Respectfully and peacefully, 
Matze

**Pull request closed without merging**
